// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MessageAnalysisML
{
    public partial class MessageAnalysisMLModel
    {
        /// <summary>
        /// model input class for MessageAnalysisMLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Spam")]
            public float Spam { get; set; }

            [ColumnName(@"Message")]
            public string Message { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MessageAnalysisMLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Spam")]
            public uint Spam { get; set; }

            [ColumnName(@"Message")]
            public float[] Message { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }
            public bool Prediction { get; internal set; }
        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MessageAnalysisMLModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
